In [1]:
import torch
print(torch.__version__)

1.9.0+cu102


## Tensor Initialization

In [2]:
device="cuda" if torch.cuda.is_available() else "cpu"

In [3]:
mytensor=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,device="cpu")
print(mytensor)
print(mytensor.dtype)
print(mytensor.device)
print(mytensor.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
cpu
torch.Size([2, 3])


In [ ]:
#other initialization


x=torch.empty(size=(3,3))
y=torch.zeros((5,5))
print(x)
print(y)

tensor([[2.1036e+37, 3.0674e-41, 1.2268e+37],
        [3.0674e-41, 1.2269e+37, 3.0674e-41],
        [1.2269e+37, 3.0674e-41, 1.2271e+37]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [ ]:
x=torch.rand((5,5))
print(x)
print(x.mean())
print(x.std())

tensor([[0.7852, 0.3146, 0.0183, 0.4115, 0.3555],
        [0.3906, 0.6538, 0.2453, 0.9137, 0.2244],
        [0.9891, 0.7300, 0.8580, 0.9738, 0.4550],
        [0.4704, 0.4490, 0.3324, 0.4505, 0.0519],
        [0.9617, 0.8944, 0.8244, 0.4751, 0.2992]])
tensor(0.5411)
tensor(0.2943)


In [ ]:
x=torch.linspace(10,20,30) # 30 numbers between 10 and 20
print(x)

tensor([10.0000, 10.3448, 10.6897, 11.0345, 11.3793, 11.7241, 12.0690, 12.4138,
        12.7586, 13.1034, 13.4483, 13.7931, 14.1379, 14.4828, 14.8276, 15.1724,
        15.5172, 15.8621, 16.2069, 16.5517, 16.8966, 17.2414, 17.5862, 17.9310,
        18.2759, 18.6207, 18.9655, 19.3103, 19.6552, 20.0000])


In [ ]:
#type conversion


tensor=torch.arange(4)
print(tensor.bool())
print(tensor.long())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3])


In [ ]:
#Array to numpy conversion


import numpy as np

arr=np.ones((5,5))
tensor=torch.from_numpy(arr)
tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

# Tensor Maths

In [4]:
x=torch.tensor([1,2,3])
y=torch.tensor([6,7,8])

#add

z1= x+y
print(z1)

#divide
z=torch.true_divide(x,y)
print(z)





tensor([ 7,  9, 11])
tensor([0.1667, 0.2857, 0.3750])


In [5]:
#inplace operations

t=torch.zeros(3)
t.add_(x) #underscore= in place

z=x**2
print(z)


#matrix multiplication
x=torch.rand((2,3))
y=torch.rand((3,5))
z=torch.mm(x,y)
print(z)

tensor([1, 4, 9])
tensor([[0.4151, 0.1840, 0.2776, 0.4498, 0.3287],
        [0.4878, 0.2657, 0.5682, 0.4418, 0.1217]])


In [6]:
#batch matrix multiplication

batch=32
n=10
m=20
p=30

tensor1=torch.rand((batch,n,m)) # 3d matrix 
tensor2=torch.rand((batch,m,p))

res=torch.bmm(tensor1,tensor2)
print(res.shape)

torch.Size([32, 10, 30])


In [7]:
#broadcasting


x1=torch.rand((5,5))
x2=torch.rand((1,5))

z=x1-x2
print(z)

tensor([[-0.5229, -0.0374,  0.2356, -0.3563, -0.3221],
        [ 0.0192, -0.4516,  0.7869,  0.1797, -0.5022],
        [-0.5798, -0.5663, -0.0958, -0.3866,  0.1488],
        [-0.2695, -0.1562,  0.6244,  0.1686, -0.7017],
        [-0.5780, -0.2143, -0.0533, -0.0777,  0.0520]])


In [8]:
#some useful functions
print(x)
sum_x=torch.sum(x,dim=0)
print(sum_x)
values,idx=torch.max(x,dim=0)
print(values)

tensor([[0.2178, 0.3034, 0.1979],
        [0.4578, 0.0272, 0.4734]])
tensor([0.6756, 0.3306, 0.6712])
tensor([0.4578, 0.3034, 0.4734])


## Tensor Indexing

In [11]:
batch_size=10
features=25
x=torch.rand((batch_size,features))

print(x[0].shape)
print(x[2,0:5])

torch.Size([25])
tensor([0.2757, 0.8663, 0.6896, 0.9229, 0.6373])


In [15]:
#torch reshaping

x=torch.arange(9)
x_3=x.reshape(3,3)
x_3
y=x_3.t() #transpose
print(y)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [19]:
#concat

x1=torch.rand((2,5))
x2=torch.rand((2,5))
print(torch.cat((x1,x2),dim=0).shape)


#unroll

batch=64
x=torch.rand((batch,2,5))
z=x.view(batch,-1)
print(z.shape)



#switch axis

z=x.permute(0,2,1) # 1st dimention at place , other 2 swaped
print(z.shape)

torch.Size([4, 5])
torch.Size([64, 10])
torch.Size([64, 5, 2])
